#!/bin/sh

################################################################################
# xcraft-dev-rules - BEGIN
################################################################################

jsfiles=$(git diff --cached --name-only --diff-filter=ACM "*.js" "*.jsx" | tr '\n' ' ')
[ -z "$jsfiles" ] && exit 0

if [ -f "node_modules/.bin/prettier" ]; then
  bin="node_modules/.bin/prettier"
else
  rootdir=$(cat .git | sed 's,gitdir: \(.*\)/\.git.*,\1,')
  if [ -f "$rootdir/node_modules/.bin/prettier" ]; then
    bin="$rootdir/node_modules/.bin/prettier"
  else
    echo >&2 "node_modules/.bin/prettier is not available"
    echo >&2 "Please, install your modules with `npm install`."
    exit 1
  fi
fi

diffs=$($bin -l $jsfiles)
[ -z "$diffs" ] && exit 0

echo "here"
echo >&2 "Javascript files must be formatted with prettier."
echo >&2 "Please run:"
echo >&2 "./node_modules/.bin/prettier --write "$diffs""
echo >&2 "or install the prettier-atom module in the Atom editor"
echo >&2 "and the prettier-vscode module in the VS Code editor"

exit 1

################################################################################
# xcraft-dev-rules - END
################################################################################
