#!/bin/sh
jsfiles=$(git diff --cached --name-only --diff-filter=ACM | grep '\.jsx\?$' | tr '\n' ' ')
[ -z "$jsfiles" ] && exit 0

diffs=$(node_modules/.bin/prettier-space-parenthesis -l $jsfiles)
[ -z "$diffs" ] && exit 0

echo "here"
echo >&2 "Javascript files must be formatted with prettier-space-parenthesis. Please run:"
echo >&2 "node_modules/.bin/prettier-space-parenthesis --write "$diffs""
echo >&2 "or install the prettier-atom-space-parenthesis module"

exit 1
